version: '3.0'

# Define the services/containers to be run
services:

  angular: # name of the first service
    build: ideal-angular
    ports:
    - "4200:4200" # specify port mapping

  express: # name of the second service
    build: ideal-api
    ports:
    - "3000:3000" # specify port mapping
    links:
    - database # link this service to the database service
  
  database: # name of the third service
    image: mongo
    ports:
    - "27017:27017" #specify port forwarding